import {
  Route,
  Construction,
  SignpostBig,
  BarChart3,
  Footprints,
  Mountain,
  Activity,
  Rows3,
} from "lucide-react";
import type { Service } from "@/types/service";

export const services: Service[] = [
  {
    id: "estudios-movilidad",
    title: "Estudios de movilidad",
    description:
      "Analizamos la integración de los proyectos con su entorno y la capacidad del sistema de movilidad existente.",
    details:
      "Elaboramos diagnósticos integrales de movilidad para evaluar el comportamiento de los diferentes modos de transporte. Analizamos la accesibilidad, proyectamos la demanda futura de viajes y formulamos estrategias de mitigación articuladas con la planeación urbana, bajo el cumplimiento de la normativa vigente.",
    highlights: [
      "Diagnóstico integral de la movilidad.",
      "Accesibilidad en los diferentes modos de transporte.",
      "Proyección de demanda de viajes.",
      "Estrategias de mitigación.",
      "Cumplimiento normativo.",
    ],
    icon: Footprints,
    image: "/images/SERVICIOS/estudios-movilidad-final.png",
    imageFit: "contain",
    imageWidth: 2400,
    imageHeight: 1792,
  },
  {
    id: "estudios-transito",
    title: "Estudios de tránsito",
    description: "Determinamos el impacto de un proyecto sobre la operación y capacidad del sistema vial.",
    details:
      "Realizamos aforos vehiculares, peatonales y de biciusuarios para obtener información primaria que permita evaluar el desempeño operacional de la red vial, su capacidad y los niveles de servicio. Además, estimamos la demanda generada por proyectos inmobiliarios y de infraestructura vial para definir soluciones que optimicen la operación y el funcionamiento de la red vial en los escenarios futuros.",
    highlights: [
      "Aforos y recolección de información.",
      "Análisis operacional de la red vial.",
      "Capacidad y niveles de servicio.",
      "Proyección de tránsito.",
      "Recomendaciones técnicas.",
      "Cumplimiento normativo.",
    ],
    icon: BarChart3,
    image: "/images/SERVICIOS/estudios-transito-final.png",
    imageFit: "contain",
    imageWidth: 2528,
    imageHeight: 1686,
  },
  {
    id: "diseno-geometrico-vias",
    title: "Diseño geométrico de vías",
    description:
      "Trazados, perfiles y secciones viales eficientes, cómodos y seguros, ajustados a la norma.",
    details:
      "Definimos el trazado horizontal y vertical, el diseño de intersecciones, así como los accesos y conexiones viales, cumpliendo la normativa técnica vigente. El resultado es un diseño optimizado para su funcionalidad, operación y seguridad vial, adaptable tanto a vías urbanas como a corredores interurbanos.",
    highlights: [
      "Trazado horizontal y vertical.",
      "Diseño de intersecciones.",
      "Accesos y conexiones viales.",
      "Cumplimiento de normas técnicas.",
      "Optimización funcional y operacional.",
    ],
    icon: Route,
    image: "/images/SERVICIOS/diseno-geometrico-vias-final.png",
    imageFit: "contain",
    imageWidth: 2528,
    imageHeight: 1696,
  },
  {
    id: "planes-manejo-transito",
    title: "Planes de manejo de tránsito",
    description: "Medidas y acciones que mitigan los impactos de las obras.",
    details:
      "Diseñamos los desvíos y el manejo de la circulación durante la obra, priorizando la seguridad de todos los usuarios de la vía con señalización temporal adecuada. Programamos el plan por etapas constructivas y gestionamos su aprobación ante la autoridad competente, para que la obra avance sin convertirse en un problema de movilidad para la ciudad.",
    highlights: [
      "Desvíos y manejo de la circulación.",
      "Seguridad para todos los usuarios.",
      "Señalización temporal.",
      "Programación por etapas constructivas.",
      "Aprobación ante la autoridad competente.",
    ],
    icon: Construction,
    image: "/images/SERVICIOS/planes-manejo-transito-final.png",
    imageFit: "contain",
    imageWidth: 3168,
    imageHeight: 1344,
  },
  {
    id: "senalizacion-vial",
    title: "Señalización vial que ordena, guía y protege",
    description: "Diseño de señalización y seguridad vial.",
    details:
      "Diseñamos la señalización horizontal y vertical y los dispositivos de seguridad vial requeridos, incluyendo demarcación y canalización del tránsito. Cada diseño cumple los manuales vigentes y se entrega con planos y especificaciones técnicas listos para construcción, sin retrasos en la aprobación.",
    highlights: [
      "Señalización horizontal y vertical.",
      "Dispositivos de seguridad vial.",
      "Demarcación y canalización.",
      "Cumplimiento de manuales vigentes.",
      "Planos y especificaciones técnicas.",
    ],
    icon: SignpostBig,
    image: "/images/SERVICIOS/senalizacion-vial-final3.png",
    imageFit: "contain",
    imageWidth: 2400,
    imageHeight: 1792,
  },
  {
    id: "diseno-semaforizacion",
    title: "Diseño de semaforización",
    description: "Señalización vial que ordena, guía y protege a todos los usuarios de la vía.",
    details:
      "Realizamos los estudios de justificación semafórica y programamos los tiempos de cada intersección, coordinando corredores completos para optimizar el flujo. El resultado son intersecciones más seguras y eficientes, con menos tiempo de espera para conductores y peatones.",
    highlights: [
      "Estudios de justificación.",
      "Programación de tiempos semafóricos.",
      "Coordinación de corredores.",
      "Optimización de intersecciones.",
      "Mejora de la seguridad vial.",
    ],
    icon: Rows3,
    image: "/images/SERVICIOS/diseno-semaforizacion-final.png",
    imageFit: "contain",
    imageWidth: 2528,
    imageHeight: 1696,
  },
  {
    id: "modelaciones-trafico",
    title: "Modelaciones de tráfico",
    description: "Anticipamos cómo se va a comportar el tránsito, antes de construir.",
    details:
      "Simulamos el comportamiento del tránsito actual y futuro mediante microsimulación, evaluando distintos escenarios antes de construir. Esto permite optimizar la operación vial, validar alternativas de diseño y dar soporte técnico sólido a la toma de decisiones, reduciendo el riesgo de ajustes costosos en obra.",
    highlights: [
      "Microsimulación actual y futura.",
      "Evaluación de escenarios futuros.",
      "Optimización de la operación vial.",
      "Validación de alternativas de diseño.",
      "Soporte para la toma de decisiones.",
    ],
    icon: Activity,
    image: "/images/SERVICIOS/modelaciones-trafico-final.png",
    imageFit: "contain",
    imageWidth: 2528,
    imageHeight: 1696,
  },
  {
    id: "diseno-explanaciones",
    title: "Diseño de explanaciones",
    description: "Optimizamos los movimientos de tierra para lograr plataformas estables y eficientes.",
    details:
      "Calculamos el balance de cortes y llenos a partir de la modelación digital del terreno, optimizando los movimientos de tierra y diseñando plataformas estables. Todo el diseño se integra con el proyecto vial, garantizando una infraestructura estable desde la base.",
    highlights: [
      "Balance de cortes y llenos.",
      "Modelación digital del terreno.",
      "Optimización de movimientos de tierra.",
      "Diseño de plataformas.",
      "Integración con el diseño vial.",
    ],
    icon: Mountain,
    image: "/images/SERVICIOS/diseno-explanaciones.jpeg",
    imageFit: "contain",
    imageWidth: 1200,
    imageHeight: 800,
  },
];
